### ISSUE TITLE
contributing guidelines 

### ISSUE THREAD

**Issue by vaibhavchellani** [gnosis/gnosis.js#49]
i would like to contribute to gnosis.js and would like to know the contributing guidelines if any .

**Comment by cag** [comment]
Ah yes, that is a good question. The short answer is: just submit a PR. They'll be reviewed, and if it isn't adjusted and merged, at least the idea and use case scenario will be taken into consideration. That said, if something is a significant time investment, consider describing the change in an issue first before you take the plunge.

As for an in depth explanation of project structure and coding guidelines, there isn't one written yet, but here are some general guidelines:

* Modify `src` and `test`. **Don't** regenerate `docs`. I'll do that before each release. It's so that the changesets for each PR is comprehensible. It also wildly inflates my contribution stats and gives me a head buzz.
* Include tests for new features and consider adding a regression test for fixes.
* Make each commit/PR about one thing if you can, but don't fret too much about this.

**Comment by vaibhavchellani** [comment]
@cag  thanks for the detailed response . I think we can close the issue now .

**Comment by cag** [comment]
You're welcome, though I will leave this open until this info is in the official docs ;)
